workflows:
  android-build:
    name: AHIR Android

    environment:
      flutter: stable

    scripts:

      - name: Android projesini oluştur
        script: |
          rm -rf android
          flutter create --platforms=android .

      - name: Gradle sürümünü Flutter ile uyumlu yap
        script: |
          sed -i.bak 's#gradle-8\.9-all\.zip#gradle-8.14-all.zip#g' android/gradle/wrapper/gradle-wrapper.properties
          cat android/gradle/wrapper/gradle-wrapper.properties

      - name: Çalışan main.dart dosyasını bağla
        script: |
          mkdir -p lib
          cp main.dart lib/main.dart

      - name: Paketleri yükle
        script: |
          flutter pub get

      - name: APK oluştur
        script: |
          flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/*.apk
