name: ahir_app
description: "Ahir Takip Ve Yönetim Uygulaması"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI ve İkonlar
  cupertino_icons: ^1.0.8

dev_dependencies:
  # Hatanın çözüldüğü doğru SDK tanımı:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Görseller ve Varlıklar
  assets:
    - assets/
    - assets/icons/
    
