name: Hayvancılık APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Kodu indir
        uses: actions/checkout@v4

      - name: Flutter kur
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Android klasörünü oluştur
        run: flutter create --platforms=android .

      - name: Kendi main.dart dosyamı kullan
        run: cp main.dart lib/main.dart

      - name: AdMob App ID ekle
        run: |
          python3 - <<'PY'
          from pathlib import Path

          manifest = Path("android/app/src/main/AndroidManifest.xml")
          text = manifest.read_text()

          app_id = '''        <meta-data
              android:name="com.google.android.gms.ads.APPLICATION_ID"
              android:value="ca-app-pub-3940256099942544~3347511713"/>'''

          if "com.google.android.gms.ads.APPLICATION_ID" not in text:
              text = text.replace("</application>", app_id + "\n    </application>")

          manifest.write_text(text)
          PY


      - name: APK'yı sakla
        uses: actions/upload-artifact@v4
        with:
          name: hayvancilik-apk
          path: build/app/outputs/flutter-apk/app-release.apk
