name: Hayvancilik APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Kodu indir
        uses: actions/checkout@v4

      - name: Flutter kur
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Android klasörünü oluştur
        run: flutter create --platforms=android .

      - name: Paketleri yükle
        run: flutter pub get

      - name: APK oluştur
        run: flutter build apk --release --enable-experiment=dot-shorthands

      - name: APK'yı sakla
        uses: actions/upload-artifact@v4
        with:
          name: hayvancilik-apk
          path: build/app/outputs/flutter-apk/app-release.apk
